### ISSUE TITLE
Can’t update through Homebrew

### ISSUE THREAD

**Issue by lor1x** [spicetify/spicetify-cli#1546]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.81.604.gccacfc8c
- Spicetify version: 2.9.2
```

### 📝 Description

Can’t update spicetify through `brew update`
go fails to install the latest version

### 📸 Screenshots

![Screen Shot 2022-03-24 at 18 27 30](https://user-images.githubusercontent.com/22913459/159990058-b454d694-983d-4129-a1d5-87ccc329ec60.png)

**Comment by ririxidev** [comment]
Update golang `x/sys` by:
`go get -u golang.org/x/sys`
it's because 1.18 breaks old x/sys from 1.17 and that's why you get this error since it's not automatically updated.

**Comment by jlcolbert** [comment]
You can't use `go get` outside of a module. You have to use `go install` with a version instead. I don't know if you mean to do that command inside of a module, or as a global install. I tried installing the way you suggested, to this message:

```
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

So I did `go install golang.org/x/sys@latest`, and got this error:

```
go: golang.org/x/sys@latest: module golang.org/x/sys@latest found (v0.0.0-20220319134239-a9b59b0215f8), but does not contain package golang.org/x/sys
```

**Comment by ririxidev** [comment]
```ruby
require "language/go"

class SpicetifyCli < Formula
  desc "Command-line tool to customize Spotify client"
  homepage "https://github.com/spicetify/spicetify-cli"
  url "https://github.com/spicetify/spicetify-cli/archive/v2.9.3.tar.gz"
  head "https://github.com/spicetify/spicetify-cli"
  sha256 "812a137b94f64e755ca876a2323f258eb7c766148a8510ce14f4546723a6c829"

  depends_on "go" => "1.17"
  
  def install
    ENV["GOPATH"] = buildpath
    path = buildpath/"dep"
    path.install Dir["*"]
    cd path do
      system "go", "build", "-ldflags", "-X main.version=#{version.to_s}", "-o", "#{bin}/spicetify"
      cp_r "./globals.d.ts", bin
      cp_r "./jsHelper", bin
      cp_r "./Themes", bin
      cp_r "./Extensions", bin
      cp_r "./CustomApps", bin
      cp_r "./css-map.json", bin
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spicetify", "-v")
  end
end
```
use this as temp fix then.

**Comment by afonsojramos** [comment]
@ririxidev is this issue being tracked on the homebrew repo?

**Comment by ririxidev** [comment]
No, it's an issue in this project,
to fix this you should add this to go.mod after line 5 (in require)
`golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8`
and this to go.sum:
`golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8 h1:OH54vjqzRWmbJ62fjuhxy7AxFFgoHN0/DPc/UrL8cAs=
golang.org/x/sys v0.0.0-20220319134239-a9b59b0215f8/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=`

**Comment by Moulick** [comment]
https://github.com/spicetify/spicetify-cli/pull/1547 should make it possible to build via go 1.18. Then once merged and released, I'll update the tap

**Comment by ririxidev** [comment]
This pr should fix it, @Moulick gj.

**Comment by theRealPadster** [comment]
The PR may fix it, but the homebrew package is still outdated or something cause I still get the error.

**Comment by afonsojramos** [comment]
Should have been updated now!
