### ISSUE TITLE
Problem in playlists

### ISSUE THREAD

**Issue by Guonejo** [spicetify/spicetify-cli#2910]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.33.1039.g8ddb5918
- Spicetify version: v2.34.0
```

### 📝 Description

When you want to click on profile covers, albums, playlists, etc. It does not allow it due to the latest update. 
I tried reinstalling the themes, changing the theme and it still doesn't allow clicking on them.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/82884497/de90b73f-65aa-45ca-a394-c157cd779da0)

**Comment by rxri** [comment]
Latest spicetify update already fixed it. Please update by running `spicetify update` in preferred terminal

**Comment by Guonejo** [comment]
Problem continues with Spicetify v2.34.1

**Comment by rxri** [comment]
Well, you did not apply... `spicetify restore backup apply`

**Comment by GeorgeGedox** [comment]
This does still happen with the latest version 2.34.1

**Comment by rxri** [comment]
> This does still happen with the latest version 2.34.1

No it doesn't, if it does then at fault is your spotify's installation.

**Comment by Guonejo** [comment]
> This does still happen with the latest version 2.34.1

I solved it with powershell and the command `spicetify restore backup apply` , then I restarted the app and it was solved.

**Comment by GeorgeGedox** [comment]
This problem still persists for me and one of my friends who also uses Spicetify, we have applied the latest update via `spicetify update` and running `spicetify restore backup apply`, we have confirmed that we're both on the latest version with `spicetify -v`, restarted the client multiple times and I also did a full clean reinstall (including removing all temporary files, cache and appdata directories) and this problem still exists.

My intention is to raise awareness that this indeed still a bug, but I see this getting ignored instead of addressed. If my comments are being considered as spam or annoying then I will simply stop reporting any bug or regression I find.

**Comment by Guonejo** [comment]
> This problem still persists for me and one of my friends who also uses Spicetify, we have applied the latest update via `spicetify update` and running `spicetify restore backup apply`, we have confirmed that we're both on the latest version with `spicetify -v`, restarted the client multiple times and I also did a full clean reinstall (including removing all temporary files, cache and appdata directories) and this problem still exists.
> 
> My intention is to raise awareness that this indeed still a bug, but I see this getting ignored instead of addressed. If my comments are being considered as spam or annoying then I will simply stop reporting any bug or regression I find.

Do you have the Microsoft store version or the Spotify web version installed?

**Comment by GeorgeGedox** [comment]
Direct installer from Spotify, not the windows store.

**Comment by Guonejo** [comment]
> Direct installer from Spotify, not the windows store.

What if you try an older version of Spotify? You may have a temporary solution

**Comment by rxri** [comment]
> This problem still persists for me and one of my friends who also uses Spicetify, we have applied the latest update via `spicetify update` and running `spicetify restore backup apply`, we have confirmed that we're both on the latest version with `spicetify -v`, restarted the client multiple times and I also did a full clean reinstall (including removing all temporary files, cache and appdata directories) and this problem still exists.
> 
> My intention is to raise awareness that this indeed still a bug, but I see this getting ignored instead of addressed. If my comments are being considered as spam or annoying then I will simply stop reporting any bug or regression I find.

That's fine. It's your choice in the end to report bugs or not. We are not going to fix anything, because there's nothing to fix. The issue has been resolved and everything works perfectly on version that it happened on. If you use experimental features, we do not support them.
If you're curious, there's my installation, so you know that I test it on latest version:
```
Spotify for Windows (32 bit)
1.2.33.1039.g8ddb5918
Spicetify vDev
xpui_2024-03-08_1709865429512_8ddb591
cef_122.1.8+g40272b5+chromium-122.0.6261.69
Runtime: Chrome
```
