### ISSUE TITLE
Incorrect Function Error

### ISSUE THREAD

**Issue by Afkwtf** [spicetify/spicetify-cli#3024]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.37.701.ge66eb7bc
- Spicetify version: v
```

### 📝 Description

When running most spicetify commands (apply, refresh, etc), I get the following error: BOM: read C:\Users\me\AppData\Roaming\Spotify\prefs: Incorrect function.

When checking the spotify prefs folder, it's empty.

### 📸 Screenshots

<img width="384" alt="Capture" src="https://github.com/spicetify/spicetify-cli/assets/169740894/30e9ca2e-647c-49be-90e8-b0cf15c673de">

**Comment by rxri** [comment]
Something is up on your end

**Comment by Afkwtf** [comment]
FYI, I fixed this by manually locating the prefs file, which was in another location, it was within C:\Users\YOUR_USERNAME\AppData\Roaming\Spotify\Users\USERNAME

IDK how many other users have the prefs file in another location, but may be good to add to the FAQ?

**Comment by rxri** [comment]
We are aware of this prefs file, however that's not the prefs file spicetify needs. It needs the one inside `%appdata%\Spotify`

**Comment by dashiinu** [comment]
I am using the correct prefs file in the prefs_path section as you stated above and i still get this message 
BOM: read C:\Users\ImTry\AppData\Roaming\Spotify: Incorrect function. and spicetify.exe auto closes and i cannot get the marketplace to appear on spotify.
